### ISSUE TITLE
v3.2 Plans/Todo's

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#22]
- [x]  Special Prizes
- [x]  Culumative Prizes
- [x]  PlaceHolderAPI Expansion (Basic Version)
- [x]  Rewrite how to detect no items 
- [x]  More formats
- [x]  PlaceHolders in Format.yml ignore casing (Mostly)
- [x]  Change ChanceReward to ExtraReward
- [x]  Add more to /av sites [site]
- [x]  Make new stuff preloaded
- [x]  Bug/Feature testing
- [x]  Cleanup plugin page on spigot  
- [x]  Create wiki for ExtraRewards/Cumulative Rewards
- [x]  Improve wiki
