### ISSUE TITLE
4.0 CheckList

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#89]
Release aim: (July 10-30)
- [x] Better way to get items than item id's
- [x] Rewrite handing of votesites
- [x] Config improvements
- [x] Particles on vote
- [x] New reward system (Seperate file for reward, config what reward file to use on giving rewards) [Needs testing]
- [x] Titles (Will require TitleAPI)
- [x] Add titles to rewards
- [x] Optimize background tasks
- [x] Potion effects rewards
- [x] Command Alias System - With Tab complete 
- [x] Update VoteParty with new Reward System 
- [x] TopVoterAwards use new reward system
- [x] Include version info in /av report
- [x] New help system
- [x] Right clicking top voter signs - #80 [WIP]
- [x] Scoreboards on commands
- [x] Json (Hovering text)
- [x] Better vote reminding (Titles, effects, sounds, etc)
- [x] Change how top voter and vote today data is prestored
- [x] pages for /av help
- [x] report files are placed in report folder
- [x] Remove need of uuid.yml
- [x] Command to reset player totals
- [x] Add /av updatecheck
- [x] Version info in /av reload
- [x] Command to check votesite
- [x] Command to see rewards like votesites
- [x] Better documentation
- [x] Command aliases for admin commands
- [x] More randomized rewards
- [x] Precentage of votes for all sites
- [x] Tidy up
