### ISSUE TITLE
4.1 CheckList

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#96]
Planned Release: July 16-19
- [x] Only show commands in /v help or /av help that you have permission to (With option)
- [x] Set durability on items
- [x] Chances can be decimals
- [x] Take Rewards (Somewhat)
- [x] Run reward files in VoteReminding.yml
- [x] Timed/delayed rewards (Untested)
- [x] Daily/Weekly top voter (Untested)
- [x] Voting points (To be used in other plugins for achivements, etc)?
- [x] Change numberofvotes to cumulative
- [x] Skulls
- [x] Merge vote party addon to plugin?
- [x] Option to change timezone on resets for top voter awards
- [x] Add placeholder for points (need to release expansion)
- [x] Player name in items/rewards
- [x] Improve top voter sorting
- [x] More scoreboards:
  - [x] /vtoday
  - [x] /vtotal
  - [x] Option to disable scoreboards
- [x] Exp in reward files
- [x] Bug fixes
- [ ] More commands to set values?
- [ ] Better rewards the more you vote?
- [ ] Other plugins support?
- [ ] Web scripts?
- [ ] Delay between votes/broadcasts?
- [ ] Add preset values in newly generated reward files?
