### ISSUE TITLE
4.2 CheckList

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotingPlugin#99]
Release Aim: July 26-29
- [x] Option to disable storing top voters for daily/weekly/monthly
- [x] Different rewards for online/offline votes (Requires offline vote rewrite)
- [x] Set the message in Rewards/VoteReminding.yml to not be "You were given rewards" by default
- [x] Run reward files in Config.yml on vote of any site
- [x] More cumulative reward options (allow mutliple cumulative rewards) (needs testing)
- [x] Allow users to change how /vote is setup
  More rewards:
  - [x] ActionBar
  - [x] BossBar
  - [x] Random Amounts of Exp (like  #money)
- [x] Don't depend on other plugins for titles,etc (Now built in)
